# Generated by Django 2.2.16 on 2020-10-30 20:51

from django.db import migrations, models


def postgres_migration_prep(apps, schema_editor):
    Address = apps.get_model("address_book", "Address")
    PhoneNumber = apps.get_model("address_book", "PhoneNumber")
    Venue = apps.get_model("address_book", "Venue")
    fields = ("street2", "type")

    for field in fields:
        filter_param = {"{}__isnull".format(field): True}
        update_param = {field: ""}
        Address.objects.filter(**filter_param).update(**update_param)

    PhoneNumber.objects.filter(
        type__isnull=True,
    ).update(type="")
    Venue.objects.filter(
        url__isnull=True,
    ).update(url="")


class Migration(migrations.Migration):

    dependencies = [
        ("address_book", "0002_auto_20200730_0934"),
    ]

    operations = [
        migrations.RunPython(postgres_migration_prep, migrations.RunPython.noop)
    ]
