# Generated by Django 3.1.4 on 2020-12-18 00:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("address_book", "0004_auto_20201030_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="date_added",
            field=models.DateTimeField(auto_now=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="address",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="address",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="date_added",
            field=models.DateTimeField(auto_now=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="date_added",
            field=models.DateTimeField(auto_now=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="venuetype",
            name="date_added",
            field=models.DateTimeField(auto_now=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="venuetype",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="venuetype",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
