# Generated by Django 3.1.5 on 2021-01-12 01:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dens', '0005_auto_20201030_1549'),
        ('committees', '0007_auto_20201217_1706'),
        ('address_book', '0005_auto_20201217_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='date added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_all', models.BooleanField(default=False, verbose_name='all active members')),
                ('is_listed_on_contact_page', models.BooleanField(default=False, verbose_name='listed on contact us page')),
                ('committees', models.ManyToManyField(blank=True, related_name='distribution_lists', to='committees.Committee')),
                ('dens', models.ManyToManyField(blank=True, related_name='distribution_lists', to='dens.Den')),
            ],
            options={
                'verbose_name': 'distribution list',
                'verbose_name_plural': 'distribution lists',
            },
        ),
    ]
