# Generated by Django 3.1.5 on 2021-01-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address_book", "0006_distributionlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="distributionlist",
            old_name="is_listed_on_contact_page",
            new_name="contact_us",
        ),
    ]
