# Generated by Django 3.1.5 on 2021-01-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0009_auto_20210112_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='name',
        ),
    ]
