# Generated by Django 4.2.3 on 2023-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address_book", "0014_auto_20210720_1640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="street2",
            field=models.CharField(blank=True, max_length=128, verbose_name="Unit / Apartment / Suite"),
        ),
        migrations.AlterField(
            model_name="address",
            name="type",
            field=models.CharField(
                blank=True, choices=[("H", "Home"), ("W", "Work"), ("O", "Other"), (None, "Type")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("H", "Home"), ("M", "Mobile"), ("W", "Work"), ("O", "Other"), (None, "Type")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="venue",
            name="url",
            field=models.URLField(blank=True, verbose_name="Website"),
        ),
    ]
