# Generated by Django 2.2.16 on 2020-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_auto_20200730_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street2',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Unit / Apartment / Suite'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('W', 'Work'), ('O', 'Other'), (None, 'Type')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('M', 'Mobile'), ('W', 'Work'), ('O', 'Other'), (None, 'Type')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='venue',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='Website'),
        ),
    ]
