# Generated by Django 3.2.21 on 2023-09-20 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_alter_category_color_alter_category_description_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['event'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendars.event'),
        ),
    ]
