# Generated by Django 3.2.21 on 2023-09-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0020_alter_committeemember_year'),
        ('attendance', '0002_auto_20230919_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committees.committee'),
        ),
    ]
