# Generated by Django 3.2.21 on 2023-09-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_committee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='member',
            new_name='members',
        ),
    ]
