# Generated by Django 2.2.14 on 2020-07-30 16:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Group Mailbox',
                'verbose_name_plural': 'Group Mailboxes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_field', models.CharField(max_length=128)),
                ('subject', models.CharField(blank=True, max_length=64)),
                ('body', tinymce.models.HTMLField(blank=True)),
                ('to_field', models.ManyToManyField(to='dens.Den')),
            ],
        ),
    ]
