# Generated by Django 2.2.17 on 2020-11-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0002_remove_message_to_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
