[tool.curlylint]
include = '\.(html|jinja)$'
exclude = '''
(
  /(
      \.eggs           # exclude a few common directories in the root of the project
    | \.git
    | \.venv
  )/
  | webpack-stats.html # also separately exclude a file named webpack-stats.html in the root of the project
)
'''

[tool.curlylint.rules]
aria_role = true
django_forms_rendering = 'as_p'
image_alt = true
indent = 2
html_has_lang = 'en-US'
meta_viewport = true
no_autofocus = true
tabindex_no_positive = true

[tool.isort]
profile = "black"
multi_line_output = 3
combine_as_imports = true
default_section = "THIRDPARTY"
include_trailing_comma = true
known_django = "django"
known_first_party = "packman"
no_lines_before = "LOCALFOLDER"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
skip = "migrations"

[tool.black]
extend-exclude = 'migrations'
