[tool.curlylint]
include = '\.(html|jinja)$'
exclude = '''
(
  /(
      \.eggs           # exclude a few common directories in the root of the project
    | \.git
    | \.venv
  )/
  | webpack-stats.html # also separately exclude a file named webpack-stats.html in the root of the project
)
'''

[tool.curlylint.rules]
aria_role = true
django_forms_rendering = 'as_p'
image_alt = true
indent = 2
html_has_lang = 'en-US'
meta_viewport = true
no_autofocus = true
tabindex_no_positive = true

[tool.isort]
extend_skip = "migrations"
profile = "black"
known_django = "django"
known_first_party = "packman"
sections = ['FUTURE', 'STDLIB', 'DJANGO', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']

[tool.black]
line-length = 119
extend-exclude = "/migrations"
