# Generated by Django 3.1.4 on 2020-12-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_squashed_0005_auto_20201103_1356'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='pack_calend_name_9f0ea3_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='pack_calend_name_15e45d_idx',
        ),
        migrations.RemoveIndex(
            model_name='packyear',
            name='pack_calend_year_0368db_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='calendars_c_name_fec224_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name', 'venue', 'location', 'start', 'end', 'category'], name='calendars_e_name_7ac5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='packyear',
            index=models.Index(fields=['year'], name='calendars_p_year_8752fb_idx'),
        ),
    ]
