# Generated by Django 3.1.5 on 2021-01-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20201217_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packyear',
            options={'ordering': ('-year',), 'verbose_name': 'pack year', 'verbose_name_plural': 'pack years'},
        ),
        migrations.AddField(
            model_name='packyear',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='packyear',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='packyear',
            name='year',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='year'),
        ),
    ]
