# Generated by Django 2.2.6 on 2019-10-12 16:31

from django.db import migrations, models
import membership.models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=membership.models.avatar_upload_location),
        ),
    ]
