# Generated by Django 3.2.7 on 2021-09-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-last_updated',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='quota',
            old_name='quota',
            new_name='target',
        ),
    ]
