# Generated by Django 3.2.7 on 2021-10-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20211002_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='image',
            field=models.ImageField(blank=True, upload_to='campaigns/', verbose_name='image'),
        ),
    ]
