# Generated by Django 3.2.7 on 2021-10-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_additional_meta_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'get_latest_by': 'ordering_opens', 'ordering': ('-ordering_opens',), 'permissions': [('generate_order_report', 'Can generate an order report')], 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
    ]
