# Generated by Django 3.2.7 on 2021-10-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_add_order_report_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gps_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='accuracy'),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
    ]
