# Generated by Django 4.2.3 on 2023-07-07 18:51

from django.db import migrations, models
import django.db.models.deletion
import packman.calendars.models


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0006_alter_category_color_alter_category_description_and_more"),
        ("campaigns", "0011_alter_prizeselection_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="year",
            field=models.ForeignKey(
                default=packman.calendars.models.PackYear.get_current,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="calendars.packyear",
            ),
        ),
    ]
