# Generated by Django 5.2.16 on 2026-09-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0012_alter_campaign_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="ordering_closes",
            field=models.DateTimeField(
                help_text="The final date and time when all orders must be submitted.", verbose_name="sales close"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="ordering_opens",
            field=models.DateTimeField(
                help_text="The date and time when members can start taking orders.", verbose_name="sales open"
            ),
        ),
    ]
