# Generated by Django 5.2.16 on 2026-09-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0013_alter_campaign_ordering_closes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="award_ineligible",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text=(
                    "Select Yes to exclude this order from leaderboards, quota progress, medals, and prize points."
                ),
                null=True,
                verbose_name="award ineligible",
            ),
        ),
    ]
