# Generated by Django 5.2.16 on 2026-09-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0014_order_award_ineligible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="ordering_opens",
            field=models.DateTimeField(
                help_text="The date and time when members can start taking orders. This date anchors the seven weekly leaderboard windows and should not be changed after the campaign starts.",
                verbose_name="sales open",
            ),
        ),
    ]
