# Generated by Django 5.2.16 on 2026-09-30 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0015_alter_campaign_ordering_opens"),
        ("membership", "0013_scout_scouting_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignScout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "exempt",
                    models.BooleanField(
                        default=False,
                        help_text="This Cub is not required to meet the campaign quota.",
                        verbose_name="exempt",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scouts",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "scout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="membership.scout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Scout Setting",
                "verbose_name_plural": "Campaign Scout Settings",
                "constraints": [
                    models.UniqueConstraint(fields=("campaign", "scout"), name="unique_campaign_scout_settings")
                ],
            },
        ),
    ]
