# Generated by Django 3.2.2 on 2021-06-04 06:01

from django.db import migrations, models
import django.utils.timezone
import uuid


def convert_datefield_to_datetimefield(apps, schema_editor):
    Family = apps.get_model("membership", "family")
    for family in Family.objects.all():
        family.datetime_added = django.utils.timezone.datetime(family.date_added.year, family.date_added.month, family.date_added.day, 0, 0, 0, 0)
        family.save()


def convert_datetimefield_to_datefield(apps, schema_editor):
    Family = apps.get_model("membership", "family")
    for family in Family.objects.all():
        family.date_added = django.utils.timezone.datetime.date(family.datetime_added.year, family.datetime_added.month, family.datetime_added.day)
        family.save()


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20210114_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='datetime_added',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time this entry was first added to the database.', verbose_name='created'),
        ),
        migrations.RunPython(convert_datefield_to_datetimefield, reverse_code=convert_datetimefield_to_datefield),
        migrations.RemoveField(
            model_name='family',
            name='date_added',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='datetime_added',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='family',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this entry was last changed in the database.', verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='family',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time this entry was first added to the database.', verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this entry was last changed in the database.', verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='member',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
