# Generated by Django 5.2.6 on 2025-09-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0010_alter_family_name_alter_family_pack_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scout",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Application Withdrawn"),
                    (1, "Applied"),
                    (2, "Denied"),
                    (3, "Approved"),
                    (4, "Active"),
                    (5, "Inactive"),
                    (6, "Graduated"),
                    (7, "Waitlist"),
                ],
                default=1,
                help_text="What is the Cub's current status? A new cub who has not been reviewed will start as 'Applied'. Membership can choose then to approve or decline the application, or make them active. Once a Cub is no longer active in the pack, either through graduation or attrition, note that change' here. Any adult member connected to this Cub will get access only once the Cub's status is 'Active' or 'Approved'.",
                verbose_name="Status",
            ),
        ),
    ]
