# Generated by Django 5.2.15 on 2026-08-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0011_alter_scout_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scout",
            options={"ordering": ["-date_added"], "verbose_name": "Cub", "verbose_name_plural": "Cubs"},
        ),
    ]
