# Generated by Django 3.2.21 on 2023-09-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_member_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_id',
        ),
        migrations.AddField(
            model_name='member',
            name='bsa_member_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='BSA Member ID'),
        ),
    ]
