# Generated by Django 3.2.21 on 2023-09-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_member_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_id',
        ),
        migrations.AddField(
            model_name='member',
            name='bsa_member_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='BSA Member ID'),
        ),
    ]
