# Generated by Django 5.2.16 on 2026-09-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0012_alter_scout_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="scout",
            name="scouting_membership_expires_on",
            field=models.DateField(
                blank=True,
                help_text="The date the Cub's Scouting America registration lapses if it is not renewed.",
                null=True,
                verbose_name="Membership Expires",
            ),
        ),
        migrations.AddField(
            model_name="scout",
            name="scouting_membership_id",
            field=models.CharField(
                blank=True,
                help_text="The member ID printed on the Cub's Scouting America membership card.",
                max_length=32,
                verbose_name="Scouting America Membership ID",
            ),
        ),
    ]
