# Generated by Django 3.1.6 on 2021-02-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('<i class="fas fa-award"></i>', 'Award'), ('<i class="fas fa-bell"></i>', 'Bell'), ('<i class="fas fa-calendar-alt"></i>', 'Calendar'), ('<i class="fas fa-campground"></i>', 'Campground'), ('<i class="fas fa-times-circle"></i>', "Circled 'X'"), ('<i class="fas fa-donate"></i>', 'Donate'), ('<i class="fas fa-exclamation-triangle"></i>', 'Exclamation'), ('<i class="fas fa-gift"></i>', 'Gift box'), ('<i class="fas fa-users"></i>', 'Group (large)'), ('<i class="fas fa-user-friends"></i>', 'Group (small)'), ('<i class="fas fa-hands-helping"></i>', 'Hands Helping'), ('<i class="fas fa-handshake"></i>', 'Hands Shaking'), ('<i class="fas fa-heart"></i>', 'Heart'), ('<i class="fas fa-medal"></i>', 'Medal'), ('<i class="fas fa-ribbon"></i>', 'Ribbon'), ('<i class="fas fa-desktop"></i>', 'Computer Screen'), ('<i class="fas fa-seedling"></i>', 'Seedling'), ('<i class="fas fa-star"></i>', 'Star')], default='', help_text='Optionally choose an icon to display with these events', max_length=64),
        ),
    ]
