# Generated by Django 2.2.6 on 2019-10-11 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('page', models.CharField(choices=[('HOME', 'Home Page'), ('ABOUT', 'About Us Page'), ('HISTORY', 'History Page')], max_length=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'get_latest_by': 'published_on',
            },
        ),
    ]
