# Generated by Django 2.2.16 on 2020-10-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201030_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='ContentBlocks',
        ),
        migrations.RemoveIndex(
            model_name='contentblocks',
            name='pages_conte_title_2e151e_idx',
        ),
        migrations.AddIndex(
            model_name='contentblocks',
            index=models.Index(fields=['title', 'published_on'], name='pages_conte_title_43e30f_idx'),
        ),
    ]
