# Generated by Django 5.2.16 on 2026-08-28 03:53

import django.db.models.deletion
import packman.calendars.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendars", "0006_alter_category_color_alter_category_description_and_more"),
        ("membership", "0012_alter_scout_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time this entry was first added to the database.",
                        verbose_name="created",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time this entry was last changed in the database.",
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Shown to families so they know what is being asked of them and how to satisfy it.",
                        verbose_name="description",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[("CUB", "Cubs"), ("ADULT", "Adults"), ("FAMILY", "Families")],
                        default="CUB",
                        help_text="Who must satisfy this requirement? Family requirements are tracked once per family.",
                        max_length=6,
                        verbose_name="applies to",
                    ),
                ),
                (
                    "tracks_expiration",
                    models.BooleanField(
                        default=True,
                        help_text="Check this box if the requirement must be renewed, such as a medical form.",
                        verbose_name="expires",
                    ),
                ),
                (
                    "default_duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If set, an expiration date is suggested this many days after the completion date.",
                        null=True,
                        verbose_name="valid for",
                    ),
                ),
                (
                    "include_contributors",
                    models.BooleanField(
                        default=False,
                        help_text="Also track this requirement for adults who are Friends of the Pack rather than a parent or guardian of an active Cub.",
                        verbose_name="include friends of the pack",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to stop tracking this requirement without deleting the records already collected.",
                        verbose_name="active",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, null=True, verbose_name="sort order")),
            ],
            options={
                "verbose_name": "Requirement",
                "verbose_name_plural": "Requirements",
                "ordering": ("sort_order", "name"),
                "indexes": [
                    models.Index(fields=["slug", "applies_to", "is_active"], name="compliance__slug_046ff2_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="RequirementRecord",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time this entry was first added to the database.",
                        verbose_name="created",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time this entry was last changed in the database.",
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "Not started"), ("OK", "Complete"), ("NA", "Waived")],
                        default="NEW",
                        max_length=3,
                        verbose_name="status",
                    ),
                ),
                ("completed_on", models.DateField(blank=True, null=True, verbose_name="completed")),
                ("expires_on", models.DateField(blank=True, null=True, verbose_name="expires")),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Do not record medical details here. Note only what is needed to track the paperwork.",
                        verbose_name="notes",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_records",
                        related_query_name="requirement_record",
                        to="membership.family",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for requirements tracked once for the whole family.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_records",
                        related_query_name="requirement_record",
                        to="membership.member",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_requirement_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        related_query_name="record",
                        to="compliance.requirement",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        default=packman.calendars.models.PackYear.get_current,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_records",
                        related_query_name="requirement_record",
                        to="calendars.packyear",
                        verbose_name="pack year",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requirement Record",
                "verbose_name_plural": "Requirement Records",
                "ordering": ("-year", "requirement__sort_order", "requirement__name"),
                "permissions": [
                    ("manage_records", "Can record and edit membership requirements for any family"),
                    ("view_all_records", "Can view membership requirement status for all families"),
                ],
                "indexes": [
                    models.Index(fields=["year", "requirement", "status"], name="compliance__year_id_23158b_idx"),
                    models.Index(fields=["family", "year"], name="compliance__family__0ba9a4_idx"),
                    models.Index(fields=["expires_on"], name="compliance__expires_f58263_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("member__isnull", False)),
                        fields=("requirement", "year", "member"),
                        name="unique_member_requirement_per_year",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("member__isnull", True)),
                        fields=("requirement", "year", "family"),
                        name="unique_family_requirement_per_year",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("member__isnull", False), ("family__isnull", False), _connector="OR"),
                        name="requirement_record_has_a_subject",
                    ),
                ],
            },
        ),
    ]
