# Generated by Django 5.2.16 on 2026-09-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_seed_default_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Recorded by leadership"),
                    ("SA_MEMBERSHIP", "Scouting America membership on the member"),
                ],
                default="MANUAL",
                help_text="Most requirements are marked off by leadership. A derived one reads its standing off the member instead, and can lapse part way through the year.",
                max_length=13,
                verbose_name="source",
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="applies_to",
            field=models.CharField(
                choices=[("CUB", "Cubs"), ("ADULT", "Adults"), ("LEADER", "Pack Leaders"), ("FAMILY", "Families")],
                default="CUB",
                help_text="Who must satisfy this requirement? Family requirements are tracked once per family.",
                max_length=6,
                verbose_name="applies to",
            ),
        ),
        migrations.AlterField(
            model_name="requirementrecord",
            name="status",
            field=models.CharField(
                choices=[("NEW", "Not started"), ("OK", "Complete"), ("NA", "Waived"), ("EXP", "Expired")],
                default="NEW",
                max_length=3,
                verbose_name="status",
            ),
        ),
    ]
