# Generated by Django 2.2.14 on 2020-07-30 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pack_calendar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pack_calendar', '0001_squashed_0005_auto_20201103_1356'),
        ('committees', '0002_membership_den'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='year_served',
            field=models.ForeignKey(default=pack_calendar.models.PackYear.get_current_pack_year_year, on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to='pack_calendar.PackYear'),
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(through='committees.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
