# Generated by Django 2.2.16 on 2020-10-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_auto_20200730_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
