# Generated by Django 2.2.16 on 2020-10-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief description of what the document is.'),
        ),
    ]
