# Generated by Django 2.2.16 on 2020-10-30 20:55

from django.db import migrations, models


def postgres_migration_prep(apps, schema_editor):
    Document = apps.get_model("documents", "document")
    fields = ("description", )

    for field in fields:
        filter_param = {"{}__isnull".format(field): True}
        update_param = {field: ""}
        Document.objects.filter(**filter_param).update(**update_param)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(postgres_migration_prep, migrations.RunPython.noop)
    ]
