# Generated by Django 2.2.14 on 2020-07-30 16:34

from django.db import migrations, models
import django.db.models.deletion
import packman.calendars.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membership", "0001_initial"),
        ("dens", "0001_initial"),
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="scout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="den",
                to="membership.Scout",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="year_assigned",
            field=models.ForeignKey(
                default=packman.calendars.models.PackYear.get_current_pack_year_year,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="den_memberships",
                to="calendars.PackYear",
            ),
        ),
        migrations.AddField(
            model_name="den",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dens",
                to="dens.Rank",
            ),
        ),
    ]
