# Generated by Django 3.1.5 on 2021-01-12 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0004_auto_20201030_1531"),
        ("dens", "0005_auto_20201030_1549"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="scout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="den_memberships",
                to="membership.scout",
            ),
        ),
    ]
