# Generated by Django 3.2.18 on 2023-03-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dens', '0010_alter_rank_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Lion'), (2, 'Tiger'), (3, 'Wolf'), (4, 'Bear'), (5, 'Jr. Webelos'), (6, 'Sr. Webelos'), (7, 'Webelos'), (8, 'Arrow of Light')], unique=True),
        ),
    ]
