# Generated by Django 4.2.3 on 2023-07-07 18:46

from django.db import migrations, models
import django.db.models.deletion
import packman.calendars.models


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0006_alter_category_color_alter_category_description_and_more"),
        ("dens", "0012_membership_unique_membership_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="year_assigned",
            field=models.ForeignKey(
                default=packman.calendars.models.PackYear.get_current,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="den_memberships",
                to="calendars.packyear",
            ),
        ),
    ]
