# Generated by Django 3.1.4 on 2020-12-18 00:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='id',
        ),
        migrations.AddField(
            model_name='choice',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='choice',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='question',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='question',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
        migrations.AddField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='vote',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
    ]
