# Generated by Django 2.2.16 on 2020-10-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0004_auto_20201030_1355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
