# Generated by Django 3.1.4 on 2020-12-18 01:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0006_auto_20201030_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="date_added",
            field=models.DateTimeField(auto_now=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="committee",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="committee",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="date_added",
            field=models.DateTimeField(auto_now=True, verbose_name="date added"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="last updated"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
