# Generated by Django 3.2.4 on 2021-06-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0010_auto_20210603_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='is_staff',
            new_name='are_staff',
        ),
    ]
