# Generated by Django 3.2.4 on 2021-06-22 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committees', '0013_rename_membership_committeemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', related_query_name='committee_member', to='committees.committee'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', related_query_name='committee_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
