# Generated by Django 3.2.4 on 2021-06-22 07:19

from django.db import migrations, models
import django.db.models.deletion
import packman.calendars.models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_alter_packyear_options'),
        ('committees', '0015_auto_20210622_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='year',
            field=models.ForeignKey(default=packman.calendars.models.PackYear.get_current_pack_year_year, on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', related_query_name='committee_membership', to='calendars.packyear', verbose_name='year served'),
        ),
        migrations.AddConstraint(
            model_name='committeemember',
            constraint=models.UniqueConstraint(fields=('year', 'committee', 'member', 'den'), name='unique_assignment_each_year'),
        ),
    ]
