# Generated by Django 2.2.16 on 2020-10-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201030_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks',
                                    to='pages.Page'),
        ),
    ]
