# Generated by Django 2.2.16 on 2020-10-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_auto_20201030_1415"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentblocks",
            options={
                "ordering": ["-published_on"],
                "verbose_name": "Content Block",
                "verbose_name_plural": "Content Blocks",
            },
        ),
    ]
