# Generated by Django 2.2.17 on 2020-11-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_auto_20201103_1300"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="categories",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
