# Generated by Django 3.2 on 2021-04-09 17:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210303_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='section body'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='section heading'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='visibility',
            field=models.CharField(choices=[('S', 'Members Only'), ('P', 'Everyone'), ('A', 'Anonymous / Guests')], default='S', help_text="'Members Only' content will only be viewable to active members or contributors. Content marked as 'Everyone' will be viewable by anyone on the website, including applicants, alumni, and anonymous visitors. Anonymous content will be displayed only if no user is logged-in.", max_length=1, verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='page',
            name='include_in_nav',
            field=models.BooleanField(default=False, help_text="Checking this option will add this page to the site's navigation bar. Not used for standard pages (e.g. Home, About, Sign-up, etc.) since they will always be included.", verbose_name='Include in navigation'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.CharField(blank=True, choices=[('HOME', 'Home'), ('ABOUT', 'About Us'), ('HISTORY', 'History'), ('SIGNUP', 'Join Us')], help_text='If this is going to be one of the standard pages, specify which one here.', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='A slug is the part of a URL which identifies a particular page on a website in an easy to read form. In other words, it’s the part of the URL that explains the page’s content. For this article, for example, the URL is https://example.com/slug, and the slug simply is ‘slug’.', null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='The title of this webpage. Will be shown as the top level header and, if added to the site navigation bar, as the link name.', max_length=64, verbose_name='title'),
        ),
    ]
