# Generated by Django 3.2 on 2021-04-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210409_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('image', models.ImageField(upload_to='pages', verbose_name='image')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.AddField(
            model_name='contentblock',
            name='images',
            field=models.ManyToManyField(related_name='contentblocks', to='pages.Image'),
        ),
    ]
