# Generated by Django 3.2.13 on 2022-05-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20210720_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
