# Generated by Django 3.2.13 on 2022-05-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_delete_images_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'verbose_name': 'Content Block', 'verbose_name_plural': 'Content Blocks'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='contentblock',
            order_with_respect_to='page',
        ),
    ]
