# Generated by Django 3.2.13 on 2022-05-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_content_block_ordering_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='bookmark',
            field=models.SlugField(blank=True, null=True, help_text='Bookmarks are used to allow readers to jump to specific parts of a webpage.', verbose_name='bookmark'),
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.UniqueConstraint(fields=('page', 'bookmark'), name='unique_bookmark_for_page'),
        ),
    ]
