# Generated by Django 5.2.16 on 2026-09-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0025_alter_contentblock_options_contentblock_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentblock",
            options={
                "ordering": ("order", "page"),
                "verbose_name": "Content Block",
                "verbose_name_plural": "Content Blocks",
            },
        ),
    ]
