# Generated by Django 5.2.16 on 2026-09-08 02:31

from django.db import migrations, models

# Mirrors the hardcoded slug lists this migration replaces, from
# packman/pages/context_processors.py (removed alongside this migration).
PINNED_PAGE_SLUGS = ["trackers"]
ABOUT_PAGE_SLUGS = ["membership-requirements", "discipline-policy", "mod-6"]

# Mirrors Page.NavPlacement (an IntegerChoices), stored numerically so the
# enum labels/names can change later without a data migration. Historical
# migration models don't carry over custom model attributes, hence the
# duplication here.
PACK_INFO = 1
PINNED = 2
ABOUT = 3
HOME = 4
SIGNUP = 5
NCC = 6

# The NCC dropdown's "Information" link previously pointed at this hardcoded
# slug from packman/pages/context_processors.py; give that page the NCC
# placement so the dropdown can look it up instead.
NCC_INFO_SLUG = "nccinfo"


def seed_nav_placement(apps, schema_editor):
    Page = apps.get_model("pages", "Page")

    # Page.page == "HOME" / "SIGNUP" are being retired in favor of their own
    # nav_placement values, so those roles no longer need a separate field.
    Page.objects.filter(page="HOME").update(nav_placement=HOME)
    Page.objects.filter(page="SIGNUP").update(nav_placement=SIGNUP)

    # Every other page: translate the old include_in_nav flag into the
    # default "Pack Info" placement (or leave it out of the nav entirely).
    # Run this before the About/History conversion below, since once those
    # pages' `page` field is nulled out they'd otherwise be swept up here too
    # and have their intentional ABOUT placement clobbered.
    for page in Page.objects.filter(page__isnull=True):
        page.nav_placement = PACK_INFO if page.include_in_nav else None
        page.save()

    # Page.ABOUT / Page.HISTORY are being retired as special "standard" page
    # types; convert their existing rows into ordinary CMS pages living under
    # the About dropdown, in the same order they always appeared in the nav.
    about = Page.objects.filter(page="ABOUT").first()
    if about is not None:
        about.page = None
        if not about.slug:
            about.slug = "about"
        about.nav_placement = ABOUT
        about.order = 0
        about.save()

    history = Page.objects.filter(page="HISTORY").first()
    if history is not None:
        history.page = None
        if not history.slug:
            history.slug = "history"
        history.nav_placement = ABOUT
        history.order = 1
        history.save()

    # Re-apply today's hardcoded pin/About overrides so behavior is unchanged.
    for order, slug in enumerate(PINNED_PAGE_SLUGS):
        Page.objects.filter(slug=slug).update(nav_placement=PINNED, order=order)
    for order, slug in enumerate(ABOUT_PAGE_SLUGS, start=2):
        Page.objects.filter(slug=slug).update(nav_placement=ABOUT, order=order)
    Page.objects.filter(slug=NCC_INFO_SLUG).update(nav_placement=NCC)


def restore_page_field(apps, schema_editor):
    Page = apps.get_model("pages", "Page")

    Page.objects.filter(nav_placement=HOME).update(page="HOME")
    Page.objects.filter(nav_placement=SIGNUP).update(page="SIGNUP")

    about = Page.objects.filter(slug="about", nav_placement=ABOUT).first()
    if about is not None:
        about.page = "ABOUT"
        about.save()

    history = Page.objects.filter(slug="history", nav_placement=ABOUT).first()
    if history is not None:
        history.page = "HISTORY"
        history.save()

    Page.objects.exclude(nav_placement=None).update(include_in_nav=True)
    Page.objects.filter(nav_placement=None).update(include_in_nav=False)


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0025_alter_contentblock_options_contentblock_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ("order", "title"), "verbose_name": "Page", "verbose_name_plural": "Pages"},
        ),
        migrations.AddField(
            model_name="page",
            name="nav_placement",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Pack Info dropdown"),
                    (2, "Pinned top-level link"),
                    (3, "About dropdown"),
                    (4, "The home page"),
                    (5, "The join us / sign-up page"),
                    (6, "NCC dropdown"),
                ],
                default=None,
                help_text=(
                    "Where this page should appear in the site's navigation bar, if at all. Leave blank to keep "
                    "this page out of the navigation bar entirely. 'The home page' and 'The join us / sign-up "
                    "page' are special: only one page may hold each, and it will be used in place of the site's "
                    "default one."
                ),
                null=True,
                verbose_name="navigation placement",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text=(
                    "Controls the order pages are listed, both in the admin and within whichever navigation "
                    "group they are placed in."
                ),
                verbose_name="order",
            ),
        ),
        # Data migration must run before the include_in_nav / page fields it
        # reads are removed below.
        migrations.RunPython(seed_nav_placement, restore_page_field),
        migrations.RemoveField(
            model_name="page",
            name="include_in_nav",
        ),
        migrations.RemoveField(
            model_name="page",
            name="page",
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                condition=models.Q(("nav_placement", HOME)),
                fields=("nav_placement",),
                name="unique_home_page",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                condition=models.Q(("nav_placement", SIGNUP)),
                fields=("nav_placement",),
                name="unique_signup_page",
            ),
        ),
    ]
