# Generated by Django 5.2

from django.db import migrations, models

# Previously, Home and Join Us were special singleton navigation placements.
# Their views queried for placements 4 and 5, then rendered the associated
# content blocks. The database constraints enforced one page per placement.
#
# Inline CMS entries now use an ordinary repeatable placement and a stable
# `cms-` slug. Host templates request the entry they need through the
# `inline_cms` template tag, while inline entries remain unavailable as
# standalone pages.
#
# This migration removes the obsolete singleton constraints, introduces the
# new placement, and converts the two existing records without replacing them
# so their content blocks and other metadata remain attached.
HOME = 4
SIGNUP = 5
INLINE_CMS = 7


def migrate_standard_pages_to_inline(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    replacements = (
        (HOME, "cms-home"),
        (SIGNUP, "cms-join-us"),
    )

    for placement, slug in replacements:
        page = Page.objects.filter(nav_placement=placement).first()
        if page is None:
            continue
        if Page.objects.exclude(pk=page.pk).filter(slug=slug).exists():
            raise RuntimeError(f"Cannot migrate page '{page}': slug '{slug}' is already in use.")
        page.nav_placement = INLINE_CMS
        page.slug = slug
        page.save(update_fields=["nav_placement", "slug"])


def restore_standard_pages(apps, schema_editor):
    """Restore usable fixed-placement records when rolling back the schema."""
    Page = apps.get_model("pages", "Page")
    # The original slugs were not part of the fixed-page lookup contract, so
    # use stable standalone slugs when returning to the old placement model.
    replacements = (
        ("cms-home", HOME, "home"),
        ("cms-join-us", SIGNUP, "signup"),
    )

    for slug, placement, restored_slug in replacements:
        page = Page.objects.filter(nav_placement=INLINE_CMS, slug=slug).first()
        if page is None:
            continue
        if Page.objects.exclude(pk=page.pk).filter(slug=restored_slug).exists():
            raise RuntimeError(f"Cannot restore page '{page}': slug '{restored_slug}' is already in use.")
        page.nav_placement = placement
        page.slug = restored_slug
        page.save(update_fields=["nav_placement", "slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0026_page_nav_placement"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="page",
            name="unique_home_page",
        ),
        migrations.RemoveConstraint(
            model_name="page",
            name="unique_signup_page",
        ),
        migrations.AlterField(
            model_name="page",
            name="nav_placement",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Pack Info dropdown"),
                    (2, "Pinned top-level link"),
                    (3, "About dropdown"),
                    (6, "NCC dropdown"),
                    (7, "Inline (CMS)"),
                ],
                default=None,
                help_text=(
                    "Where this page should be used. Leave blank to keep it out of the navigation bar. Inline "
                    "(CMS) entries are inserted into other pages by slug and cannot be opened as standalone pages."
                ),
                null=True,
                verbose_name="navigation placement",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text=(
                    "Identifies this page in URLs and templates. Inline CMS entries must start with 'cms-'. "
                    "If omitted, the prefix will be added when the page is saved."
                ),
                null=True,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.RunPython(migrate_standard_pages_to_inline, restore_standard_pages),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(nav_placement=INLINE_CMS)
                    | (models.Q(slug__isnull=False) & models.Q(slug__startswith="cms-"))
                ),
                name="inline_cms_slug_prefix",
            ),
        ),
    ]
