# Generated by Django 2.2.14 on 2020-07-30 16:34

from django.db import migrations, models
import django.db.models.deletion
import pack_calendar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        ('dens', '0001_initial'),
        ('pack_calendar', '0001_squashed_0005_auto_20201103_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='scout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='den', to='membership.Scout'),
        ),
        migrations.AddField(
            model_name='membership',
            name='year_assigned',
            field=models.ForeignKey(default=pack_calendar.models.PackYear.get_current_pack_year_year, on_delete=django.db.models.deletion.CASCADE, related_name='den_memberships', to='pack_calendar.PackYear'),
        ),
        migrations.AddField(
            model_name='den',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dens', to='dens.Rank'),
        ),
    ]
