# Generated by Django 2.2.16 on 2020-10-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dens', '0002_auto_20200730_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
