# Generated by Django 2.2.16 on 2020-10-30 20:55

from django.db import migrations, models


def postgres_migration_prep(apps, schema_editor):
    Rank = apps.get_model("dens", "Rank")
    fields = ("description", )

    for field in fields:
        filter_param = {"{}__isnull".format(field): True}
        update_param = {field: ""}
        Rank.objects.filter(**filter_param).update(**update_param)


class Migration(migrations.Migration):

    dependencies = [
        ('dens', '0002_auto_20200730_0934'),
    ]

    operations = [
        migrations.RunPython(postgres_migration_prep, migrations.RunPython.noop)
    ]
