# Generated by Django 2.2.16 on 2020-10-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dens', '0003_auto_20201030_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
