# Generated by Django 2.2.17 on 2020-11-03 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    replaces = [('pack_calendar', '0001_initial'), ('pack_calendar', '0002_auto_20201030_1355'), ('pack_calendar', '0003_auto_20201030_1403'), ('pack_calendar', '0004_auto_20201030_1554'), ('pack_calendar', '0005_auto_20201103_1356')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address_book', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(help_text='e.g. Pack Meeting, Den Meeting, Camp out, etc.', max_length=32)),
                ('description', models.CharField(blank=True, help_text='Give a little more detail about the kinds of events in this category', max_length=256, null=True)),
                ('icon', models.CharField(blank=True, choices=[('<i class="fas fa-award"></i>', 'Award'), ('<i class="fas fa-bell"></i>', 'Bell'), ('<i class="fas fa-calendar-alt"></i>', 'Calendar'), ('<i class="fas fa-campground"></i>', 'Campground'), ('<i class="fas fa-times-circle"></i>', "Circled 'X'"), ('<i class="fas fa-donate"></i>', 'Donate'), ('<i class="fas fa-exclamation-triangle"></i>', 'Exclamation'), ('<i class="fas fa-gift"></i>', 'Gift box'), ('<i class="fas fa-users"></i>', 'Group (large)'), ('<i class="fas fa-user-friends"></i>', 'Group (small)'), ('<i class="fas fa-hands-helping"></i>', 'Hands Helping'), ('<i class="fas fa-handshake"></i>', 'Hands Shaking'), ('<i class="fas fa-heart"></i>', 'Heart'), ('<i class="fas fa-medal"></i>', 'Medal'), ('<i class="fas fa-ribbon"></i>', 'Ribbon'), ('<i class="fas fa-seedling"></i>', 'Seedling'), ('<i class="fas fa-star"></i>', 'Star')], help_text='Optionally choose an icon to display with these events', max_length=64, null=True)),
                ('color', models.CharField(blank=True, choices=[('primary', 'Blue'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Teal'), ('secondary', 'Grey/Muted'), ('transparent', 'Transparent')], help_text='Optionally choose a color to display these event in.', max_length=16, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('published', models.BooleanField(default=True, verbose_name='Show on iCal')),
                ('status', models.CharField(choices=[('TENTATIVE', 'Tentative'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=9)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='PackYear',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Pack Year',
                'verbose_name_plural': 'Pack Years',
                'ordering': ('-year',),
            },
        ),
        migrations.AddIndex(
            model_name='packyear',
            index=models.Index(fields=['year'], name='pack_calend_year_0368db_idx'),
        ),
        migrations.AddField(
            model_name='event',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='events', to='documents.Document'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pack_calendar.Category'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='address_book.Venue'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='pack_calend_name_9f0ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name', 'venue', 'location', 'start', 'end', 'category'], name='pack_calend_name_15e45d_idx'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('primary', 'Blue'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Teal'), ('secondary', 'Grey/Muted'), ('transparent', 'Transparent')], default='', help_text='Optionally choose a color to display these event in.', max_length=16),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Give a little more detail about the kinds of events in this category', max_length=256),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('<i class="fas fa-award"></i>', 'Award'), ('<i class="fas fa-bell"></i>', 'Bell'), ('<i class="fas fa-calendar-alt"></i>', 'Calendar'), ('<i class="fas fa-campground"></i>', 'Campground'), ('<i class="fas fa-times-circle"></i>', "Circled 'X'"), ('<i class="fas fa-donate"></i>', 'Donate'), ('<i class="fas fa-exclamation-triangle"></i>', 'Exclamation'), ('<i class="fas fa-gift"></i>', 'Gift box'), ('<i class="fas fa-users"></i>', 'Group (large)'), ('<i class="fas fa-user-friends"></i>', 'Group (small)'), ('<i class="fas fa-hands-helping"></i>', 'Hands Helping'), ('<i class="fas fa-handshake"></i>', 'Hands Shaking'), ('<i class="fas fa-heart"></i>', 'Heart'), ('<i class="fas fa-medal"></i>', 'Medal'), ('<i class="fas fa-ribbon"></i>', 'Ribbon'), ('<i class="fas fa-seedling"></i>', 'Seedling'), ('<i class="fas fa-star"></i>', 'Star')], default='', help_text='Optionally choose an icon to display with these events', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='packyear',
            name='year',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
