# Generated by Django 2.2.16 on 2020-10-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_calendar', '0003_auto_20201030_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packyear',
            name='year',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
