# Generated by Django 2.2.17 on 2020-11-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack_calendar', '0004_auto_20201030_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendee_groups',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
