# Generated by Django 3.2.4 on 2021-07-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='distros',
            field=models.ManyToManyField(to='mail.DistributionList'),
        ),
    ]
