# Generated by Django 3.2.4 on 2021-07-26 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_remove_bcc_delivery_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='ListSettings',
        ),
    ]
