# Generated by Django 3.2.4 on 2021-07-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_rename_settings_listsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listsettings',
            name='list_from',
            field=models.CharField(blank=True, max_length=100, verbose_name='from'),
        ),
    ]
