# Generated by Django 3.2.4 on 2021-07-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20210726_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listsettings',
            name='help_email',
        ),
        migrations.AlterField(
            model_name='listsettings',
            name='from_email',
            field=models.EmailField(blank=True, help_text="The email address that emails sent from this list will originate from. If left blank, will default to the site's DEFAULT_FROM_EMAIL as specified in site settings.", max_length=254, verbose_name='from email'),
        ),
        migrations.AlterField(
            model_name='listsettings',
            name='from_name',
            field=models.CharField(blank=True, help_text='The name that will be displayed in the From line of emails sent from this list. If left blank, will default to the from email.', max_length=40, verbose_name='from name'),
        ),
        migrations.AlterField(
            model_name='listsettings',
            name='subject_prefix',
            field=models.CharField(blank=True, help_text="If provided, the subject prefix will precede every sent email's subject in the email subject field.", max_length=20, verbose_name='subject line prefix'),
        ),
    ]
