# Generated by Django 3.2.4 on 2021-07-27 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0007_remove_listsettings_help_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecipient',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipients', related_query_name='message_recipient', to='mail.message'),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipients', related_query_name='message_recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
