# Generated by Django 3.2.6 on 2021-08-16 18:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_auto_20210727_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='body'),
        ),
    ]
