# Generated by Django 4.2.3 on 2023-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_auto_20210720_1640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, help_text="Brief description of what the document is."),
        ),
    ]
